import { IBlog } from "@/types/cms";

export const dummyBlogs: IBlog[] = [
    {
        id: 1,
        title: "Glow Naturally: Top 5 Skincare Routines for Radiant Skin",
        sub_title: "Unveil the secrets to a healthy, glowing complexion",
        author: {
            id: 101,
            username: "beauty_guru_amy",
        },
        category: {
            id: 1,
            name: "Skincare",
        },
        tags: "skincare, natural glow, beauty routine",
        cover_image: "https://images.unsplash.com/photo-1519699047748-de8e457a634e?q=80&w=1480&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        description: "Discover how to achieve radiant skin using simple, natural products. This guide walks you through morning and evening routines that leave your skin refreshed and glowing.",
        slug: "top-5-skincare-routines",
        created_at: "2025-07-20T10:15:00Z",
        updated_at: "2025-07-20T10:15:00Z",
        is_active: true,
        send_as_newsletter: true,
        recommended_products: [],
    },
    {
        id: 2,
        title: "5-Minute Everyday Makeup for Busy Mornings",
        sub_title: "Look your best with minimal effort",
        author: {
            id: 102,
            username: "makeupbylisa",
        },
        category: {
            id: 2,
            name: "Makeup",
        },
        tags: "makeup, quick makeup, daily look",
        cover_image: "https://images.unsplash.com/photo-1618702999466-3282e523fb90?q=80&w=1480&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        description: "Running late? This quick makeup tutorial will have you looking polished and professional in just five minutes. Perfect for working professionals and students alike.",
        slug: "5-minute-everyday-makeup",
        created_at: "2025-07-21T08:30:00Z",
        updated_at: "2025-07-21T08:30:00Z",
        is_active: true,
        send_as_newsletter: false,
        recommended_products: [],
    },
    {
        id: 3,
        title: "Hair Care Myths Busted: What Actually Works",
        sub_title: "Stop falling for these common hair care mistakes",
        author: {
            id: 103,
            username: "haircare_herald",
        },
        category: {
            id: 3,
            name: "Hair Care",
        },
        tags: "hair care, myths, healthy hair",
        cover_image: "https://images.unsplash.com/photo-1658281097220-eb7672eed00b?q=80&w=1480&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        description: "Are you washing your hair every day? Think oils are bad? We bust the most common hair care myths and show you what really promotes healthy, beautiful hair.",
        slug: "hair-care-myths-busted",
        created_at: "2025-07-22T14:00:00Z",
        updated_at: "2025-07-22T14:00:00Z",
        is_active: true,
        send_as_newsletter: true,
        recommended_products: [],
    },
];
