export const settingData = [
  { data: "profile", title: "Profile" },
  { data: "category", title: "Category" },
  { data: "blog-category", title: "Blog Category" },
  { data: "sub-category", title: "Sub Category" },
  { data: "brand", title: "Brand" },
  { data: "attributes-and-variation", title: "Attributes and Variation" },
  // { data: "api-keys", title: "API keys" },
  // { data: "referral", title: "Referral" },
  // { data: "section-management", title: "Section Management" },
  { data: "social-links", title: "Social Links" },
  { data: "roles-and-permission", title: "Roles and Permissions" },
  { data: "order-status", title: "Order Status" },
  // { data: "preferences", title: "Preferences" },
  { data: "billings", title: "Billings" },
  { data: "seo", title: "SEO" },
  { data: "inventory-location", title: "Inventory Location" },
  { data: "taxes", title: "Taxes" },
  { data: "admin-users", title: "Admins" },
  { data: "help-and-support", title: "Help and Support" },
  { data: "privacy-policy", title: "Privacy Policy" },
  { data: "terms-and-condition", title: "Terms and Condition" },
];
