export interface Col<T> {
  title: string | React.ReactNode;
  render: (item: T) => React.ReactNode;
}

export enum ETypes {
  PRODUCTS = "products",
  CATEGORY = "category",
  BLOG_CATEGORY = "blogcategory",
  SUBCATEGORY = "subcategory",
  BRAND = "brand",
  REFERRAL = "referral",
  ORDERS = "orders",
  INVENTORY_LOCATION = "inventory-location",
  TAX = "tax",
  ADMIN = "admin",
  TRANSACTIONS = "transactions",
  INVOICES = "invoices",
  ROLES = "roles",
  ATTRIBUTE = "attribute",
  SOCIAL_LINKS = "social-links",
  BLOGS = "blogs",
  PARTNER_COMPANY = "partner-company",
  FAQ = "faq",
  BANNERS = "banners",
  NOTIFICATION = "notification",
  SECTION_MANAGEMENT = "section-management",
  ORDER_STATUS = "order-status",
  NEWSLETTERS = "newsletters",
  SMS = "sms",
  NAVIGATION_INFO = "navigation-info",
  EXPERT_RECOMMENDATION = "expert-recommendation",
  TESTIMONIAL = "testimonial",
  COUPON = "coupon",
  FLASH_SALES = "flash-sales",
  USER_MANAGEMENT = "user-management",
}

export enum ESettings {
  PROFILE = "profile",
  CATEGORY = "category",
  BLOG_CATEGORY = "blog-category",
  SUB_CATEGORY = "sub-category",
  BRAND = "brand",
  ATTRIBUTES = "attributes-and-variation",
  API_KEYS = "api-keys",
  REFERRAL = "referral",
  SECTION_MANAGEMENT = "section-management",
  SOCIAL_LINKS = "social-links",
  ROLES = "roles-and-permission",
  ORDER_STATUS = "order-status",
  PREFERENCES = "preferences",
  BILLINGS = "billings",
  SEO = "seo",
  INVENTORY_LOCATION = "inventory-location",
  TAXES = "taxes",
  ADMIN_USERS = "admin-users",
  ADD_CATEGORY = "Add Category",
  EDIT_CATEGORY = "Edit Category",
  ADD_SUB_CATEGORY = "Add Sub Category",
  EDIT_SUB_CATEGORY = "Edit Sub Category",
  ADD_BLOG_CATEGORY = "Add Blog Category",
  EDIT_BLOG_CATEGORY = "Edit Blog Category",
  ADD_BRAND = "Add Brand",
  EDIT_BRAND = "Edit Brand",
  ADD_ATTRIBUTE = "Add Attribute",
  EDIT_ATTRIBUTE = "Edit Attribute",
  ADD_REFERRAL = "Add Referral",
  EDIT_REFERRAL = "Edit Referral",
  ADD_SOCIAL_LINKS = "Add Social Links",
  EDIT_SOCIAL_LINKS = "Edit Social Links",
  ADD_TAX = "Add Tax",
  EDIT_TAX = "Edit Tax",
  ADD_ROLE = "Add Roles",
  EDIT_ROLE = "Edit  Roles",
  ADD_ORDER_STATUS = "Add Order Status",
  EDIT_ORDER_STATUS = "Edit Order Status",
  ADD_ADMIN = "Add Admin",
  EDIT_ADMIN = "Edit Admin",
  ADD_INVENTORY_LOCATION = "Add Inventory Location",
  EDIT_INVENTORY_LOCATION = "Edit Inventory Location",
}
