import { IOrders } from "@/types/orders";

export const dummyOrders: IOrders[] = Array.from({ length: 20 }).map((_, i) => ({
  id: i + 1,
  order_id: 1000 + i,
  user_id: i + 1,
  has_invoice: i % 2 === 0,
  invoice_id: 5000 + i,
  status: i % 4 === 0 ? "Placed" : i % 4 === 1 ? "Packed" : i % 4 === 2 ? "Shipped" : "Delivered",
  total_price: (100 + i * 10).toFixed(2),
  order_status: {
    id: i + 1,
    name: i % 4 === 0 ? "Placed" : i % 4 === 1 ? "Packed" : i % 4 === 2 ? "Shipped" : "Delivered",
    is_active: true,
    is_type_success: i % 2 === 0,
    is_type_failed: i % 2 !== 0,
    position: i + 1,
    primary_color: "#FF8C00",
    text_color: "#FFFFFF",
  },
  order_created: new Date(Date.now() - i * 86400000).toISOString(),
  payment_method: i % 2 === 0 ? "Credit Card" : "COD",
  discount_amount: 5,
  vat_amount: 10,
  sub_total: 100 + i * 10,
  total_amount: 105 + i * 10,
  coupon_discount: 0,
  shipping_fee: 5,
  payment_status: i % 3 === 0 ? "pending" : i % 3 === 1 ? "paid" : "failed",
  user: {
    id: i + 1,
    username: `user${i + 1}`,
    email: `user${i + 1}@example.com`,
    address: `Address ${i + 1}`,
    phone_number: `980000000${i}`,
    profile_picture: `https://placehold.co/100x100?text=User${i + 1}`,
    first_name: `First${i + 1}`,
    last_name: `Last${i + 1}`,
  },
  shipping_info: {
    id: i + 1,
    first_name: `First${i + 1}`,
    last_name: `Last${i + 1}`,
    phone_no: `980000000${i}`,
    alternate_phone_no: `981000000${i}`,
    email: `user${i + 1}@example.com`,
    address: `Street ${i + 1}`,
    city: `City${i + 1}`,
    province: `Province${i + 1}`,
    landmark: `Landmark${i + 1}`,
    building: `Building${i + 1}`,
    order_id: 1000 + i,
  },
  order_details: [
    {
      id: i + 1,
      order: 1000 + i,
      product: {
        id: i + 1,
        image: `https://placehold.co/100x100?text=Product${i + 1}`,
        name: `Product ${i + 1}`,
        sku: `SKU${i + 1}`,
        quantity: 10,
        general_description: "General description",
        detail_description: "Detail description",
        price: "20.00",
        discount_percentage: "5%",
        flash_end_date: new Date().toISOString(),
        flash_sale_discount: "2%",
        is_flash_sale: i % 2 === 0,
        slug_name: `product-${i + 1}`,
        is_published: true,
        is_Featured: i % 2 === 0,
        is_new: i % 3 === 0,
        is_must_sold: i % 4 === 0,
        is_tax_applicable: true,
        tutorial: null,
        youtube_link: null,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        brand: i + 1,
        tax_applied: "5%",
        average_rating: 4.5,
        package: [],
      },
      product_variant: {
        id: i + 1,
        item_name: `Variant ${i + 1}`,
        item_price: "20.00",
        item_quantity: 5,
        item_image: `https://placehold.co/50x50?text=Var${i + 1}`,
        sku: `SKU-VAR-${i + 1}`,
        product_variants: [],
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      quantity: 2,
      price: 20,
      total_price: 40,
      discount_amount: 5,
      vat_amount: 2,
      status: "Placed",
    },
  ],
}));
